class MSDConfig:
    tag_names = (
        'rock',
        'pop',
        'indie',
        'alternative',
        'electronic',
        'hip-hop',
        'metal',
        'jazz',
        'punk',
        'folk',
        'alternative rock',
        'indie rock',
        'dance',
        'hard rock',
        '00s',
        'soul',
        'hardcore',
        '80s',
        'country',
        'classic rock',
        'punk rock',
        'blues',
        'chillout',
        'experimental',
        'heavy metal',
        'death metal',
        '90s',
        'reggae',
        'progressive rock',
        'ambient',
        'acoustic',
        'beautiful',
        'british',
        'rnb',
        'funk',
        'metalcore',
        'mellow',
        'world',
        'guitar',
        'trance',
        'indie pop',
        'christian',
        'house',
        'spanish',
        'latin',
        'psychedelic',
        'electro',
        'piano',
        '70s',
        'progressive metal',
    )
